### ISSUE TITLE
MacOS High Sierra 10.13.6 error

### ISSUE THREAD

**Issue by davnelso** [WonderMediaProductions/Maya2glTF#49]
Hey there,

I get the following error when trying to compile on MacOS Sierra 10.13.6:

[ 46%] Building CXX object CMakeFiles/maya2glTF.dir/src/MeshVertices.cpp.o
/Users/davnelso/Documents/Maya2glTF/src/MeshVertices.cpp:422:39: error: no member named 'clamp' in namespace 'std'
                                const auto assignmentCount = std::clamp<int>(assignmentsSize - componentOffset, 0, vertexJointAssignmentElementSize);
                                                             ~~~~~^
/Users/davnelso/Documents/Maya2glTF/src/MeshVertices.cpp:422:48: error: expected '(' for function-style cast or type construction
                                const auto assignmentCount = std::clamp<int>(assignmentsSize - componentOffset, 0, vertexJointAssignmentElementSize);
                                                                        ~~~^
/Users/davnelso/Documents/Maya2glTF/src/MeshVertices.cpp:422:66: warning: expression result unused [-Wunused-value]
                                const auto assignmentCount = std::clamp<int>(assignmentsSize - componentOffset, 0, vertexJointAssignmentElementSize);
                                                                             ~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~
/Users/davnelso/Documents/Maya2glTF/src/MeshVertices.cpp:423:39: error: no member named 'clamp' in namespace 'std'
                                const auto assignmentIndex = std::clamp<int>(componentOffset, 0, assignmentsSize - assignmentCount);
                                                             ~~~~~^
/Users/davnelso/Documents/Maya2glTF/src/MeshVertices.cpp:423:48: error: expected '(' for function-style cast or type construction
                                const auto assignmentIndex = std::clamp<int>(componentOffset, 0, assignmentsSize - assignmentCount);
                                                                        ~~~^
/Users/davnelso/Documents/Maya2glTF/src/MeshVertices.cpp:423:50: warning: expression result unused [-Wunused-value]
                                const auto assignmentIndex = std::clamp<int>(componentOffset, 0, assignmentsSize - assignmentCount);
                                                                             ^~~~~~~~~~~~~~~
2 warnings and 4 errors generated.
make[2]: *** [CMakeFiles/maya2glTF.dir/src/MeshVertices.cpp.o] Error 1
make[1]: *** [CMakeFiles/maya2glTF.dir/all] Error 2
make: *** [all] Error 2

Got any quick solutions I may be missing to compile this?

Thanks,
-David.

**Comment by Ziriax** [comment]
The plugin requires a compiler that has C++17 support. Although the CMake script specifies this, it appears your system has an older version of the C++ libraries. 

I'm a Windows developer myself, just starting on OSX, so the only advice I can give you right now is to upgrade to the latest version for XCode.

What version of XCode do you have installed?

**Comment by davnelso** [comment]
Xcode was out of date. Thanks for the guidance. All good now!

**Comment by Ziriax** [comment]
Nice! Please let me know if your export works or not; we are not using the exporter on MacOS ourselves, so feedback is welcome!

**Comment by davnelso** [comment]
Looks like it does crash on export using maya 2018 on sierra. But it loads fine, and assigns the GLSL shader just fine in Maya 2018 on Mac. When I save it and load it on Windows 2018 it loads and exports fine. But export on Mac fails.

![image](https://user-images.githubusercontent.com/24258299/45379349-aca47580-b5b4-11e8-8ae9-2f7fe492ddd3.png)

I cannot provide our content to show examples but if there is a logger for debug mode and you have a test asset I'd be happy to test it for regression and provide feedback. Thanks, -David.
